export const defaultStore = {
  random: {
    loading: false,
    error: null,
    movie: {
      adult: false,
      backdrop_path: "/lEs8B5bmaTpC5zBgrMznoOVvweL.jpg",
      belongs_to_collection: null,
      budget: 20000000,
      genres: [
        {
          id: 12,
          name: "Adventure",
        },
        {
          id: 35,
          name: "Comedy",
        },
        {
          id: 14,
          name: "Fantasy",
        },
      ],
      homepage: "",
      id: 526,
      imdb_id: "tt0089457",
      original_language: "en",
      original_title: "Ladyhawke",
      overview:
        "Captain Etienne Navarre is a man on whose shoulders lies a cruel curse. Punished for loving each other, Navarre must become a wolf by night whilst his lover, Lady Isabeau, takes the form of a hawk by day. Together, with the thief Philippe Gaston, they must try to overthrow the corrupt Bishop and in doing so break the spell.",
      popularity: 21.32,
      poster_path: "/l3nRJ9Cs7C1AZ7das8S76QqwqjI.jpg",
      production_companies: [
        {
          id: 174,
          logo_path: "/zhD3hhtKB5qyv7ZeL4uLpNxgMVU.png",
          name: "Warner Bros. Pictures",
          origin_country: "US",
        },
        {
          id: 25,
          logo_path: "/qZCc1lty5FzX30aOCVRBLzaVmcp.png",
          name: "20th Century Fox",
          origin_country: "US",
        },
      ],
      production_countries: [
        {
          iso_3166_1: "US",
          name: "United States of America",
        },
      ],
      release_date: "1985-03-27",
      revenue: 18432000,
      runtime: 121,
      spoken_languages: [
        {
          english_name: "English",
          iso_639_1: "en",
          name: "English",
        },
      ],
      status: "Released",
      tagline:
        "No force in Heaven will release them. No power on Earth can save them.",
      title: "Ladyhawke",
      video: false,
      vote_average: 7,
      vote_count: 1065,
    },
  },
  login: {
    loading: false,
    error: null,
    user: null,
  },
  users: {
    ids: [],
    entities: {},
    loading: false,
    error: null,
  },
  suggestions: {
    ids: [],
    entities: {},
    loading: false,
    error: null,
  },
  trending: {
    ids: [],
    entities: {},
    loading: false,
    error: null,
  },
  theaters: {
    ids: [],
    entities: {},
    loading: false,
    error: null,
  },
  popular: {
    ids: [],
    entities: {},
    loading: false,
    error: null,
  },
  topRated: {
    ids: [],
    entities: {},
    loading: false,
    error: null,
  },
  discover: {
    ids: [],
    entities: {},
    loading: false,
    error: null,
    filters: {
      language: "",
      releaseGte: "",
      releaseLte: "",
      sortBy: "vote_average.desc",
      voteAverageGte: "",
      voteAverageLte: "",
      voteCountGte: 50,
      voteCountLte: "",
      cast: [],
      crew: [],
      genres: [],
      noGenres: [],
    },
    savedPage: 1,
  },
  bookmarks: {
    ids: [],
    entities: {},
    loading: false,
    error: null,
  },
};

export const detailedMovie = {
  adult: false,
  backdrop_path: "/lV5vLlGkZtSySMraLENUr4Fp2vJ.jpg",
  belongs_to_collection: {
    id: 458558,
    name: "Mamma Mia! Collection",
    poster_path: "/xRbDA4Ys0Y2Bvbnme02fVBwMWFe.jpg",
    backdrop_path: "/8lmFjt0Lord5vl6iGx3fRlZrBuN.jpg",
  },
  budget: 52000000,
  genres: [
    {
      id: 35,
      name: "Comedy",
    },
    {
      id: 10749,
      name: "Romance",
    },
  ],
  homepage: "http://www.mammamiamovie.com",
  id: 11631,
  imdb_id: "tt0795421",
  original_language: "en",
  original_title: "Mamma Mia!",
  overview:
    "An independent, single mother who owns a small hotel on a Greek island is about to marry off the spirited young daughter she's raised alone. But, the daughter has secretly invited three of her mother's ex-lovers in the hopes of finding her biological father.",
  popularity: 35.559,
  poster_path: "/zdUA4FNHbXPadzVOJiU0Rgn6cHR.jpg",
  production_companies: [
    {
      id: 34441,
      logo_path: null,
      name: "Littlestar",
      origin_country: "GB",
    },
    {
      id: 4171,
      logo_path: "/ip8rzankhLLhJGGkvfCirfUM26d.png",
      name: "Playtone",
      origin_country: "US",
    },
    {
      id: 2655,
      logo_path: null,
      name: "Internationale Filmproduktion Richter",
      origin_country: "DE",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "DE",
      name: "Germany",
    },
    {
      iso_3166_1: "GB",
      name: "United Kingdom",
    },
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  release_date: "2008-07-03",
  revenue: 609841637,
  runtime: 108,
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
    {
      english_name: "Greek",
      iso_639_1: "el",
      name: "ελληνικά",
    },
  ],
  status: "Released",
  tagline:
    "A mother. A daughter. Three possible fathers. A trip down the aisle you'll never forget.",
  title: "Mamma Mia!",
  video: false,
  vote_average: 6.972,
  vote_count: 6169,
  credits: {
    cast: [
      {
        adult: false,
        gender: 1,
        id: 5064,
        known_for_department: "Acting",
        name: "Meryl Streep",
        original_name: "Meryl Streep",
        popularity: 33.014,
        profile_path: "/emAAzyK1rJ6aiMi0wsWYp51EC3h.jpg",
        cast_id: 6,
        character: "Donna Sheridan",
        credit_id: "52fe446c9251416c7503427f",
        order: 0,
      },
      {
        adult: false,
        gender: 2,
        id: 517,
        known_for_department: "Acting",
        name: "Pierce Brosnan",
        original_name: "Pierce Brosnan",
        popularity: 48.1,
        profile_path: "/AdFQZh4iGRT0qjwU9hTmTtyQ1xJ.jpg",
        cast_id: 5,
        character: "Sam Carmichael",
        credit_id: "52fe446c9251416c7503427b",
        order: 1,
      },
      {
        adult: false,
        gender: 2,
        id: 5472,
        known_for_department: "Acting",
        name: "Colin Firth",
        original_name: "Colin Firth",
        popularity: 36.423,
        profile_path: "/4VBeYEUQbfhnivdkqInM36u5fda.jpg",
        cast_id: 10,
        character: "Harry Bright",
        credit_id: "52fe446c9251416c7503428b",
        order: 2,
      },
      {
        adult: false,
        gender: 2,
        id: 1640,
        known_for_department: "Acting",
        name: "Stellan Skarsgård",
        original_name: "Stellan Skarsgård",
        popularity: 22.993,
        profile_path: "/x78BtYHElirO7Iw8bL4m8CnzRDc.jpg",
        cast_id: 4,
        character: "Bill Anderson",
        credit_id: "52fe446c9251416c75034277",
        order: 3,
      },
      {
        adult: false,
        gender: 1,
        id: 477,
        known_for_department: "Acting",
        name: "Julie Walters",
        original_name: "Julie Walters",
        popularity: 32.703,
        profile_path: "/bCTkV2OUgzbJdQEoCk3GesE4DXq.jpg",
        cast_id: 7,
        character: "Rosie Mulligan",
        credit_id: "52fe446c9251416c75034283",
        order: 4,
      },
      {
        adult: false,
        gender: 1,
        id: 71070,
        known_for_department: "Acting",
        name: "Amanda Seyfried",
        original_name: "Amanda Seyfried",
        popularity: 58.635,
        profile_path: "/wcHYErlynY8xWe6X7RmqEqpMBGl.jpg",
        cast_id: 3,
        character: "Sophie Sheridan",
        credit_id: "52fe446c9251416c75034273",
        order: 5,
      },
      {
        adult: false,
        gender: 2,
        id: 55470,
        known_for_department: "Acting",
        name: "Dominic Cooper",
        original_name: "Dominic Cooper",
        popularity: 20.761,
        profile_path: "/wFPdARerxpaAaHucYGTSNqViWpn.jpg",
        cast_id: 27,
        character: "Sky Rymand",
        credit_id: "52fe446c9251416c750342e3",
        order: 6,
      },
      {
        adult: false,
        gender: 1,
        id: 11870,
        known_for_department: "Acting",
        name: "Christine Baranski",
        original_name: "Christine Baranski",
        popularity: 26.916,
        profile_path: "/x6jNFlGrzaM0LwK2GsxBNdCN41N.jpg",
        cast_id: 8,
        character: "Tanya Chesham-Leigh",
        credit_id: "52fe446c9251416c75034287",
        order: 7,
      },
      {
        adult: false,
        gender: 2,
        id: 40043,
        known_for_department: "Acting",
        name: "Niall Buggy",
        original_name: "Niall Buggy",
        popularity: 1.349,
        profile_path: "/A6PBoFbX91n7R0CkBSy33dwiQ0b.jpg",
        cast_id: 42,
        character: "Father Alex",
        credit_id: "5920789b9251414ab10468cf",
        order: 8,
      },
    ],
    crew: [
      {
        adult: false,
        gender: 2,
        id: 31,
        known_for_department: "Acting",
        name: "Tom Hanks",
        original_name: "Tom Hanks",
        popularity: 89.689,
        profile_path: "/xndWFsBlClOJFRdhSt4NBwiPq2o.jpg",
        credit_id: "52fe446c9251416c750342a5",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 1,
        id: 471,
        known_for_department: "Art",
        name: "Maria Djurkovic",
        original_name: "Maria Djurkovic",
        popularity: 1.231,
        profile_path: null,
        credit_id: "5b3497760e0a26400d01f89d",
        department: "Art",
        job: "Production Design",
      },
      {
        adult: false,
        gender: 1,
        id: 2057,
        known_for_department: "Crew",
        name: "Kim McGarrity",
        original_name: "Kim McGarrity",
        popularity: 10.164,
        profile_path: null,
        credit_id: "64a0b2498c0a48011e1c7dc5",
        department: "Crew",
        job: "Stunts",
      },
      {
        adult: false,
        gender: 1,
        id: 11072,
        known_for_department: "Editing",
        name: "Lesley Walker",
        original_name: "Lesley Walker",
        popularity: 4.445,
        profile_path: null,
        credit_id: "52fe446c9251416c750342d5",
        department: "Editing",
        job: "Editor",
      },
      {
        adult: false,
        gender: 1,
        id: 2242,
        known_for_department: "Production",
        name: "Ellen Lewis",
        original_name: "Ellen Lewis",
        popularity: 1.62,
        profile_path: null,
        credit_id: "5b3498020e0a26401602111b",
        department: "Production",
        job: "Casting",
      },
    ],
  },
  videos: {
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Mamma Mia! (2008) Official Trailer | Screen Bites",
        key: "8RBNHdG35WY",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: false,
        published_at: "2010-09-30T10:58:06.000Z",
        id: "63c481d95f2b8d00aed511c2",
      },
    ],
  },
};
